create table if not exists update_log (
  id bigint generated by default as identity primary key,
  run_at timestamp with time zone default timezone('utc'::text, now()) not null,
  mode text not null,
  start_date text,
  end_date text,
  days_count int,
  status text not null default 'success',
  message text
);

alter table update_log enable row level security;

create policy "Allow public read access"
  on update_log for select
  using (true);

create policy "Allow public insert"
  on update_log for insert
  with check (true);
